# Generated by Django 4.0.6 on 2022-07-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recomendation',
            field=models.CharField(choices=[('Must Watch', 'Must'), ('Should Watch', 'Should'), ('Avoid Watch', 'Avoid'), ('No Opinion', 'No Opinion')], default='No Opinion', max_length=50, null=True),
        ),
    ]
